### ISSUE TITLE
I can't get the bot to work

### ISSUE THREAD

**Issue by AnkayuDev** [Peanut1120/discord-verification#2]
I followed all of your instructions, but when someone joins the server, no messages or anything happens in private

**Comment by patrickmcm** [comment]
It's just using the guild member add event, so it should work fine. You sure that you have djsv12 installed?

Contact me on discord if this doesn't fix your issue, Peanut#1120

**Comment by patrickmcm** [comment]
Also, make sure that you have SERVER MEMBERS INTENT ticked in the BOT menu on your application.
![image](https://user-images.githubusercontent.com/44944178/113594381-88f02180-962f-11eb-8e67-a859c4795ec2.png)

**Comment by AnkayuDev** [comment]
Hello, the problem is solved but where should I put the html file, on my site or leave it in the bot file?

**Comment by patrickmcm** [comment]
Everything is intergrated, just put the whole site on a vps or node.js hosting site, like glitch.com or heroku.

**Comment by AnkayuDev** [comment]
I put my code on Glitch, but when a person joins I have this error 
![image](https://user-images.githubusercontent.com/73549143/113782738-ab9e3b00-9700-11eb-89e2-696ccc811495.png)

**Comment by AnkayuDev** [comment]
the problem was solved by itself

**Comment by AnkayuDev** [comment]
but I don't understand the endpoint in the link

**Comment by patrickmcm** [comment]
The way this works is like this

1. The person joins the server and gets a DM
2. The person clicks on the link in the embed
3. It takes them to the website where they first go through the discord oauth so we get there discord id
4. They do a captcha, then once it is complete we add the roles to them in the discord.

The purpose of the endpoint is to grab the discord id and to make them do a captcha.

If you still don't understand, I'll make a tutorial on how to set it up.

**Comment by AnkayuDev** [comment]
I'm sorry to bother you, but I really don't understand much, I never use html with discord.js

**Comment by AnkayuDev** [comment]
You have disabled Discord private messages

**Comment by patrickmcm** [comment]
Really? Make sure its a capital P Peanut#1120

**Comment by AnkayuDev** [comment]
![image](https://user-images.githubusercontent.com/73549143/114176136-c3e0a680-9908-11eb-8413-d2156df6d9c8.png)

**Comment by patrickmcm** [comment]
Click on add friend and I'll accept it so we can talk

**Comment by AnkayuDev** [comment]
problem solved
