### ISSUE TITLE
Bot don´t add a role

### ISSUE THREAD

**Issue by Chines29** [Peanut1120/discord-verification#3]
I configured everything as said but when someone solves the captcha does not receive any role

**Comment by patrickmcm** [comment]
Hey! Could you go into your heroku console and show me the logs when you try and do the captcha?

Get to the heroku logs by doing this:
![0FyruIMp](https://user-images.githubusercontent.com/44944178/114284775-28efe580-9a4a-11eb-8f1f-cd64991af8d3.gif)

**Comment by Chines29** [comment]
![image](https://user-images.githubusercontent.com/81709962/114285744-7ae83980-9a51-11eb-9510-6d8b3aa53f24.png)

**Comment by patrickmcm** [comment]
Yeah, could you try verify, keeping the console open then show me the output from that.

So just keep the console open, attempt to verify, then show me the console afterwards.

**Comment by Chines29** [comment]
When i try verify the console don´t change

**Comment by patrickmcm** [comment]
Have you tried doing it on an secondary account?

**Comment by Chines29** [comment]
Yes

**Comment by patrickmcm** [comment]
Contact me on discord Peanut#1120, we can talk further.
